# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-28 22:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortly', '0002_remove_userprofile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='urls',
            old_name='oryginal_url',
            new_name='original_url',
        ),
    ]
